In [25]:
import pandas as pd

ge3 = pd.read_excel(
    "../data/raw/GSE80970_MSACF_raw_methylated_ClassLabel.xlsx",
    header=None
)

# load without header

In [26]:
print(ge3.shape)
ge3.head()

(485579, 144)

,0,1,2,3,4,5,6,7,8,9,...,134,135,136,137,138,139,140,141,142,143
0,Class Label (AD-1 and Normal-0),1,0,1,0,0,1,1,0,0,...,1,1,0,1,1,0,0,0,0,74.0
1,ID_REF,MS66AC,MS546AC,MS709AC,MS1549AC,MS82AC,MS752AC,MS504AC,MS842AC,MS915AC,...,MS1017AC,MS1076AC,MS1124AC,MS364AC,MS462AC,MS1358AC,MS1163AC,MS900AC,MS978AC,NaN
2,cg00000029,3140,2869,2927,2927,3760,3060,3689,3350,3727,...,3077,2740,3383,2992,3121,1719,2431,3735,1996,NaN
3,cg00000108,6039,5853,7623,6377,6395,6523,6826,7645,7704,...,6705,5435,7042,6238,6251,5245,4844,7931,5762,NaN
4,cg00000109,2172,1782,3556,2449,2365,2332,2146,2917,2716,...,2759,2008,2441,1789,2348,1364,1580,2678,1651,NaN

In [27]:
ge3 = ge3.iloc[:, :-1]

# remove last invalid column

In [28]:
print(ge3.shape)
print(ge3.iloc[0, -5:])

(485579, 143)
138    1
139    0
140    0
141    0
142    0
Name: 0, dtype: object

In [29]:
ge3_labels = ge3.iloc[0, 1:].values.astype(int)

# extract class labels

In [30]:
print(len(ge3_labels))
print(ge3_labels[:10])
print(set(ge3_labels))

142
[1 0 1 0 0 1 1 0 0 1]
{np.int64(0), np.int64(1)}

In [31]:
ge3_data = ge3.iloc[2:].copy()

# remove label row and sample ID row

In [32]:
print(ge3_data.shape)
ge3_data.head()

(485577, 143)

,0,1,2,3,4,5,6,7,8,9,...,133,134,135,136,137,138,139,140,141,142
2,cg00000029,3140,2869,2927,2927,3760,3060,3689,3350,3727,...,2461,3077,2740,3383,2992,3121,1719,2431,3735,1996
3,cg00000108,6039,5853,7623,6377,6395,6523,6826,7645,7704,...,5202,6705,5435,7042,6238,6251,5245,4844,7931,5762
4,cg00000109,2172,1782,3556,2449,2365,2332,2146,2917,2716,...,1887,2759,2008,2441,1789,2348,1364,1580,2678,1651
5,cg00000165,1082,838,1103,822,1050,1150,947,1253,1008,...,829,947,743,1014,967,801,424,678,1001,605
6,cg00000236,3902,3323,5063,3044,3830,3793,3506,4368,3835,...,3060,3671,3365,3692,3346,3540,1620,2562,4464,2456

In [33]:
 gene_ids_3 = ge3_data.iloc[:, 0]
ge3_data = ge3_data.iloc[:, 1:]

# separate feature IDs and numeric values

In [34]:
print(gene_ids_3.head())
print(ge3_data.shape)
ge3_data.head()

2    cg00000029
3    cg00000108
4    cg00000109
5    cg00000165
6    cg00000236
Name: 0, dtype: object
(485577, 142)

,1,2,3,4,5,6,7,8,9,10,...,133,134,135,136,137,138,139,140,141,142
2,3140,2869,2927,2927,3760,3060,3689,3350,3727,2795,...,2461,3077,2740,3383,2992,3121,1719,2431,3735,1996
3,6039,5853,7623,6377,6395,6523,6826,7645,7704,5518,...,5202,6705,5435,7042,6238,6251,5245,4844,7931,5762
4,2172,1782,3556,2449,2365,2332,2146,2917,2716,1418,...,1887,2759,2008,2441,1789,2348,1364,1580,2678,1651
5,1082,838,1103,822,1050,1150,947,1253,1008,832,...,829,947,743,1014,967,801,424,678,1001,605
6,3902,3323,5063,3044,3830,3793,3506,4368,3835,2951,...,3060,3671,3365,3692,3346,3540,1620,2562,4464,2456

In [35]:
ge3_data = ge3_data.apply(pd.to_numeric, errors='coerce')

# ensure all values are numeric

In [36]:
print(ge3_data.dtypes.unique())
print(ge3_data.isnull().sum().sum())

[dtype('int64')]
0

In [37]:
import numpy as np

ge3_data = ge3_data.astype(np.float32)

# reduce memory usage

In [38]:
print(ge3_data.dtypes.unique())

[dtype('float32')]

In [39]:
ge3_data = pd.DataFrame(ge3_data.values.T, columns=gene_ids_3)

# convert from features × samples → samples × features

In [40]:
print(ge3_data.shape)
print(ge3_data.columns[:5])

(142, 485577)
Index(['cg00000029', 'cg00000108', 'cg00000109', 'cg00000165', 'cg00000236'], dtype='object', name=0)

In [41]:
np.save("../data/processed/GSE80970_data.npy", ge3_data.values)

# save methylation data

np.save("../data/processed/GSE80970_labels.npy", ge3_labels)

# save labels

In [42]:
import numpy as np

data_check = np.load("../data/processed/GSE80970_data.npy")
labels_check = np.load("../data/processed/GSE80970_labels.npy")

print(data_check.shape)
print(len(labels_check))

(142, 485577)
142

In [43]:
import pandas as pd

ge1 = pd.read_excel(
    "../data/raw/GSE33000_raw_data_2 class_PFC_dataset_ClassDenoted (2).xlsx",
    engine="openpyxl"
)

# load dataset faster

In [44]:
print(ge1.shape)

(39281, 469)

In [45]:
ge1_labels = ge1.iloc[-1, 1:].values.astype(int)

# extract labels from last row

In [46]:
print(len(ge1_labels))
print(set(ge1_labels))

468
{np.int64(0), np.int64(1), np.int64(157)}

In [47]:
ge1_labels = ge1.iloc[-1, 1:-1].values.astype(int)

# remove first column AND last invalid column

In [48]:
print(len(ge1_labels))
print(set(ge1_labels))

467
{np.int64(0), np.int64(1)}

In [49]:
ge1_data = ge1.iloc[:-1, :]

# remove last row (labels)

In [50]:
print(ge1_data.shape)

(39280, 469)

In [51]:
gene_ids_1 = ge1_data.iloc[:, 0]
ge1_data = ge1_data.iloc[:, 1:-1]

# remove first column (gene names) and last invalid column

In [52]:
print(ge1_data.shape)

(39280, 467)

In [53]:
ge1_data = ge1_data.apply(pd.to_numeric, errors='coerce')

# ensure all values are numeric

In [54]:
print(ge1_data.isnull().sum().sum())

250991

In [55]:
ge1_data = ge1_data.fillna(ge1_data.mean())

# fill missing values using column mean

In [56]:
print(ge1_data.isnull().sum().sum())

0

In [57]:
import numpy as np

ge1_data = ge1_data.astype(np.float32)

# reduce memory usage

In [58]:
print(ge1_data.dtypes.unique())

[dtype('float32')]

In [59]:
ge1_data = pd.DataFrame(ge1_data.values.T, columns=gene_ids_1)

# convert to samples × features

In [60]:
print(ge1_data.shape)

(467, 39280)

In [61]:
np.save("../data/processed/GSE33000_data.npy", ge1_data.values)

# save data

np.save("../data/processed/GSE33000_labels.npy", ge1_labels)

# save labels

In [62]:
import numpy as np

data_check = np.load("../data/processed/GSE33000_data.npy")
labels_check = np.load("../data/processed/GSE33000_labels.npy")

print(data_check.shape)
print(len(labels_check))

(467, 39280)
467

In [70]:
ge2 = pd.read_csv(
    "../data/raw/GSE44770_series_matrix_ClassLabel.txt",
    sep="\t",
    header=None,
    skiprows=1,
    low_memory=False
)

# skip metadata line

In [71]:
print(ge2.iloc[0, :10])

0    Class Label (AD-1, N-0)
1                          1
2                          1
3                          0
4                          0
5                          1
6                          1
7                          0
8                          1
9                          0
Name: 0, dtype: object

In [72]:
row0 = ge2.iloc[0].values

# take label row

row0 = pd.to_numeric(row0, errors='coerce')

# convert to numeric

ge2_labels = row0[1:]  # remove first column

ge2_labels = ge2_labels[~pd.isna(ge2_labels)].astype(int)

# clean labels

In [73]:
print(len(ge2_labels))
print(set(ge2_labels))

231
{np.int64(0), np.int64(1), np.int64(100)}

In [74]:
ge2_labels = ge2_labels[ge2_labels != 100]

# remove invalid label

In [75]:
print(len(ge2_labels))
print(set(ge2_labels))

230
{np.int64(0), np.int64(1)}

In [76]:
ge2_data = ge2.iloc[2:, :]

# remove first two rows

In [77]:
print(ge2_data.shape)

(39281, 232)

In [78]:
ge2_data = ge2.iloc[3:, :]

# remove first 3 rows properly

In [79]:
print(ge2_data.shape)

(39280, 232)

In [80]:
gene_ids_2 = ge2_data.iloc[:, 0]
ge2_data = ge2_data.iloc[:, 1:-1]

# remove gene names and last invalid column

In [81]:
print(ge2_data.shape)

(39280, 230)

In [82]:
ge2_data = ge2_data.apply(pd.to_numeric, errors='coerce')

# ensure numeric

In [83]:
print(ge2_data.isnull().sum().sum())

572

In [84]:
ge2_data = ge2_data.fillna(ge2_data.mean())

# fill missing using column mean

In [85]:
print(ge2_data.isnull().sum().sum())

0

In [86]:
import numpy as np

ge2_data = ge2_data.astype(np.float32)

# reduce memory usage

In [87]:
print(ge2_data.dtypes.unique())

[dtype('float32')]

In [88]:
ge2_data = pd.DataFrame(ge2_data.values.T, columns=gene_ids_2)

# convert to samples × features

In [89]:
print(ge2_data.shape)

(230, 39280)

In [90]:
np.save("../data/processed/GSE44770_data.npy", ge2_data.values)

# save data

np.save("../data/processed/GSE44770_labels.npy", ge2_labels)

# save labels

In [1]:
import numpy as np

data_check = np.load("../data/processed/GSE44770_data.npy")
labels_check = np.load("../data/processed/GSE44770_labels.npy")

print(data_check.shape)
print(len(labels_check))

(230, 39280)
230

In [2]:
import numpy as np

ge1_data = np.load("../data/processed/GSE33000_data.npy")
ge1_labels = np.load("../data/processed/GSE33000_labels.npy")

ge2_data = np.load("../data/processed/GSE44770_data.npy")
ge2_labels = np.load("../data/processed/GSE44770_labels.npy")

# load both GE datasets

In [3]:
print(ge1_data.shape, len(ge1_labels))
print(ge2_data.shape, len(ge2_labels))

(467, 39280) 467
(230, 39280) 230

In [4]:
combined_data = np.vstack((ge1_data, ge2_data))

# combine samples

combined_labels = np.hstack((ge1_labels, ge2_labels))

# combine labels

In [5]:
print(combined_data.shape)
print(len(combined_labels))

(697, 39280)
697

In [6]:
np.save("../data/processed/combined_data.npy", combined_data)
np.save("../data/processed/combined_labels.npy", combined_labels)

In [7]:
X = np.load("../data/processed/combined_data.npy")
y = np.load("../data/processed/combined_labels.npy")

print(X.shape, len(y))

(697, 39280) 697